-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Feb 11, 2024 at 06:07 AM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mn`
--

-- --------------------------------------------------------

--
-- Table structure for table `orderparts`
--

DROP TABLE IF EXISTS `orderparts`;
CREATE TABLE IF NOT EXISTS `orderparts` (
  `oid` int NOT NULL AUTO_INCREMENT,
  `pid` int NOT NULL,
  `qty` int NOT NULL,
  PRIMARY KEY (`oid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `parts`
--

DROP TABLE IF EXISTS `parts`;
CREATE TABLE IF NOT EXISTS `parts` (
  `pid` int NOT NULL AUTO_INCREMENT,
  `category` varchar(20) NOT NULL,
  `name` varchar(20) NOT NULL,
  `description` varchar(500) NOT NULL,
  `price` int NOT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `parts`
--

INSERT INTO `parts` (`pid`, `category`, `name`, `description`, `price`) VALUES
(1, 'BP', 'Muffler', 'Two-wheeler silencers are used to silence the noise generated by the engine while throwing out hot flue gases from the combustion chamber.', 35000),
(2, 'BP', 'Side Mirror', 'Helping the driver see areas behind and to the sides of the vehicle, outside the driver’s peripheral vision. (in the blind spot)', 1280),
(3, 'BP', 'Gas Tank', 'Motorcycle fuel tanks store and supply gasoline for the engine and hence are fundamental to the machine’s operation. Additionally, because the fuel the tank holds is highly flammable and volatile, safety is the priority in its construction.', 20000),
(4, 'LL', 'Rear Tail Lamp Light', 'The main purpose of taillights is to help other drivers see the motorcycle on the road.', 4750),
(5, 'LL', 'Single Lamp Set', 'One of the lights on a vehicle that flashes to show in which direction the driver is intending to turn.', 3400),
(6, 'LL', 'Halogen Head Lamps', 'A halogen lamp is an incandescent lamp consisting of a tungsten filament sealed in a compact transparent envelope that Is filled with a mixture of an inert gas and a small amount of a halogen , such as iodine or bromine.', 7300),
(7, 'SP', 'Chains', 'Unsealed chains, also referred to as “Standard Roller Chain”, are simply a series of metal links that from plain bearing.', 8600),
(8, 'SP', 'Sparking Plugs', 'The sparking plug is a fundamental component of your bike’s ignition system. This spark ignites the air-fuel mixture in the combustion chamber, causing an explosion that starts the engine power stroke.', 3400),
(9, 'SP', 'Battery', 'Motorcycle battery is an electrical energy storage system that users a reversible chemical interaction between the lead and the acid in the battery to store electrical energy.', 11500);

-- --------------------------------------------------------

--
-- Table structure for table `supplier`
--

DROP TABLE IF EXISTS `supplier`;
CREATE TABLE IF NOT EXISTS `supplier` (
  `sid` int NOT NULL AUTO_INCREMENT,
  `name` varchar(20) NOT NULL,
  `contact` int NOT NULL,
  PRIMARY KEY (`sid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `uorder`
--

DROP TABLE IF EXISTS `uorder`;
CREATE TABLE IF NOT EXISTS `uorder` (
  `uoid` int NOT NULL AUTO_INCREMENT,
  `date` date NOT NULL,
  `amount` int NOT NULL,
  `uid` int NOT NULL,
  PRIMARY KEY (`uoid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `uid` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  PRIMARY KEY (`uid`)
) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`uid`, `name`, `password`, `email`) VALUES
(1, 'Prasa', '8934ef576238c92a45d3f49eebc792f1', 'Prasa@gmail.com'),
(10, 'Mum', 'eef5e5e9d7f8fb259fb84ea0619afa59', 'MumthazDeen@gmail.com'),
(11, 'ab', '123456', 'a'),
(9, 'Sasi', '54f79eb0053fea7d829e86f7e7ce9d7f', 'Sasi@Gmail.com');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
